name: Backend API CI

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/ontology-api

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test # nếu chưa có thì bạn có thể dùng: echo "No tests yet"

    - name: Lint check
      run: npm run lint || echo "Linting not configured"
